# Mesa/Vulkan packages for hardware-accelerated Wayland rendering.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libegl-mesa0 \
        libglx-mesa0 \
        libvulkan1 \
        mesa-utils \
        mesa-vulkan-drivers \
        vulkan-tools \
        wayland-utils
