# Redistributable system fonts for prototypes and browser automation.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fontconfig \
        fonts-firacode \
        fonts-liberation \
        fonts-noto-color-emoji \
        fonts-noto-core
